### ISSUE TITLE
Less: Unhandled event loop exception

### ISSUE THREAD

**Issue by ianbrandt** [vtst/ow#23]
After following the install instructions I get this on startup:

```
eclipse.buildId=M20120208-0800
java.version=1.6.0_29
java.vendor=Apple Inc.
BootLoader constants: OS=macosx, ARCH=x86, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product -keyring /Users/ibrandt/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws cocoa -arch x86 -product org.eclipse.epp.package.jee.product -clean -keyring /Users/ibrandt/.eclipse_keyring -showlocation

Error
Mon Apr 09 18:11:55 PDT 2012
org.eclipse.xtext.builder.impl.XtextBuilder  - 


java.lang.NullPointerException
    at org.eclipse.xtext.builder.builderState.MarkerUpdaterImpl.updateMarker(MarkerUpdaterImpl.java:56)
    at org.eclipse.xtext.builder.builderState.AbstractBuilderState.updateMarkers(AbstractBuilderState.java:76)
    at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.doUpdate(ClusteringBuilderState.java:264)
    at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:107)
    at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:158)
    at org.eclipse.xtext.builder.impl.XtextBuilder.incrementalBuild(XtextBuilder.java:141)
    at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:91)
    at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:728)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:199)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:239)
    at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:292)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:295)
    at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:351)
    at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:374)
    at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
    at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

And when I try to open a trivial test.less file:

```
.testClass {
    color: blue;
}
```

...with the Less Editor I get:

```
eclipse.buildId=M20120208-0800
java.version=1.6.0_29
java.vendor=Apple Inc.
BootLoader constants: OS=macosx, ARCH=x86, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product -keyring /Users/ibrandt/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws cocoa -arch x86 -product org.eclipse.epp.package.jee.product -clean -keyring /Users/ibrandt/.eclipse_keyring -showlocation

Error
Mon Apr 09 18:15:24 PDT 2012
Unhandled event loop exception

org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.Error: Unresolved compilation problem: 
    The method createEObjectDescriptions(EObject, IAcceptor<IEObjectDescription>) of type LessResourceDescriptionStrategy must override a superclass method
)
    at org.eclipse.swt.SWT.error(SWT.java:4282)
    at org.eclipse.swt.SWT.error(SWT.java:4197)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:138)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3938)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3615)
    at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
    at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
    at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
    at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:123)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:344)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:622)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:577)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1410)
Caused by: java.lang.Error: Unresolved compilation problem: 
    The method createEObjectDescriptions(EObject, IAcceptor<IEObjectDescription>) of type LessResourceDescriptionStrategy must override a superclass method

    at net.vtst.ow.eclipse.less.resource.LessResourceDescriptionStrategy.createEObjectDescriptions(LessResourceDescriptionStrategy.java:25)
    at org.eclipse.xtext.resource.impl.DefaultResourceDescription.computeExportedObjects(DefaultResourceDescription.java:88)
    at org.eclipse.xtext.resource.impl.DefaultResourceDescription$4.get(DefaultResourceDescription.java:172)
    at org.eclipse.xtext.resource.impl.DefaultResourceDescription$4.get(DefaultResourceDescription.java:1)
    at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:72)
    at org.eclipse.xtext.resource.impl.DefaultResourceDescription.getLookUp(DefaultResourceDescription.java:167)
    at org.eclipse.xtext.resource.impl.AbstractResourceDescription.getExportedObjects(AbstractResourceDescription.java:32)
    at org.eclipse.xtext.ui.editor.StatefulResourceDescription.copyExportedObjects(StatefulResourceDescription.java:48)
    at org.eclipse.xtext.ui.editor.StatefulResourceDescription.<init>(StatefulResourceDescription.java:44)
    at org.eclipse.xtext.ui.editor.DocumentBasedDirtyResource.copyState(DocumentBasedDirtyResource.java:93)
    at org.eclipse.xtext.ui.editor.DocumentBasedDirtyResource.initiallyProcessResource(DocumentBasedDirtyResource.java:53)
    at org.eclipse.xtext.builder.impl.PersistentDataAwareDirtyResource.initiallyProcessResource(PersistentDataAwareDirtyResource.java:35)
    at org.eclipse.xtext.ui.editor.DocumentBasedDirtyResource$1.process(DocumentBasedDirtyResource.java:40)
    at org.eclipse.xtext.ui.editor.DocumentBasedDirtyResource$1.process(DocumentBasedDirtyResource.java:1)
    at org.eclipse.xtext.util.concurrent.IUnitOfWork$Void.exec(IUnitOfWork.java:36)
    at org.eclipse.xtext.util.concurrent.AbstractReadWriteAcces.readOnly(AbstractReadWriteAcces.java:32)
    at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:78)
    at org.eclipse.xtext.ui.editor.DocumentBasedDirtyResource.connect(DocumentBasedDirtyResource.java:36)
    at org.eclipse.xtext.ui.editor.DirtyStateEditorSupport.initDirtyResource(DirtyStateEditorSupport.java:330)
    at org.eclipse.xtext.ui.editor.DirtyStateEditorSupport.initializeDirtyStateSupport(DirtyStateEditorSupport.java:273)
    at org.eclipse.xtext.ui.editor.AbstractDirtyStateAwareEditorCallback.afterCreatePartControl(AbstractDirtyStateAwareEditorCallback.java:32)
    at org.eclipse.xtext.builder.nature.NatureAddingEditorCallback.afterCreatePartControl(NatureAddingEditorCallback.java:29)
    at org.eclipse.xtext.ui.editor.CompoundXtextEditorCallback.afterCreatePartControl(CompoundXtextEditorCallback.java:49)
    at org.eclipse.xtext.ui.editor.XtextEditor.createPartControl(XtextEditor.java:431)
    at org.eclipse.ui.internal.EditorReference.createPartHelper(EditorReference.java:670)
    at org.eclipse.ui.internal.EditorReference.createPart(EditorReference.java:465)
    at org.eclipse.ui.internal.WorkbenchPartReference.getPart(WorkbenchPartReference.java:595)
    at org.eclipse.ui.internal.EditorReference.getEditor(EditorReference.java:289)
    at org.eclipse.ui.internal.EditorManager.findEditor(EditorManager.java:424)
    at org.eclipse.ui.internal.EditorManager.findEditor(EditorManager.java:402)
    at org.eclipse.ui.internal.WorkbenchPage.findEditor(WorkbenchPage.java:2178)
    at org.eclipse.ui.NavigationLocation.getEditorPart(NavigationLocation.java:44)
    at org.eclipse.ui.texteditor.TextSelectionNavigationLocation.update(TextSelectionNavigationLocation.java:320)
    at org.eclipse.ui.internal.NavigationHistory.updateEntry(NavigationHistory.java:470)
    at org.eclipse.ui.internal.NavigationHistory.access$9(NavigationHistory.java:466)
    at org.eclipse.ui.internal.NavigationHistory$2.run(NavigationHistory.java:200)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
    ... 22 more
```

I've tried restarting Eclipse with '-clean', but there was no improvement.

**Comment by ianbrandt** [comment]
Also the TMF Xtext version I installed was "TMF Xtext-2.1.1 (2.1.x)".

**Comment by vtst** [comment]
Thanks for the bug report. It seems that your problem could be the same as the one reported in the issue #24. I just released a version 1.0.3 of the plugin which should solve it. Could you please give it a try, and let me know whether it now works?

**Comment by levito** [comment]
Seems fixed for me. I'll keep testing - using the editor every day. (Xtext 2.2.1, LESS editor 1.0.3, Indigo 3.7.2 Java EE on Java 1.6)

**Comment by vtst** [comment]
Ok, thanks a lot for the feedback.

**Comment by ianbrandt** [comment]
Sorry, I missed the notifications for this.  I just tested 1.0.3, and the issue is fixed for me as well.

Thanks!
