### ISSUE TITLE
JS: NullPointerException on compile run target

### ISSUE THREAD

**Issue by SanjayVas** [vtst/ow#50]
I've got the same configuration in both Mac OSX and Windows 7 64-bit. This works on the Mac, but not on my Windows machine.

``` java.lang.NullPointerException
    at java.io.File.<init>(Unknown Source)
    at net.vtst.ow.eclipse.js.closure.launching.compiler.ClosureCompilerProcess$ErrorInfo.<init>(ClosureCompilerProcess.java:93)
    at net.vtst.ow.eclipse.js.closure.launching.compiler.ClosureCompilerProcess$StreamMonitorErrorManager.println(ClosureCompilerProcess.java:135)
    at com.google.javascript.jscomp.BasicErrorManager.generateReport(BasicErrorManager.java:58)
    at com.google.javascript.jscomp.Compiler.compileModules(Compiler.java:564)
    at net.vtst.ow.eclipse.js.closure.launching.compiler.ClosureCompilerLaunchConfigurationDelegate.launch(ClosureCompilerLaunchConfigurationDelegate.java:125)
    at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:854)
    at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:703)
    at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:937)
    at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1141)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

Interestingly, the same source also shows various errors in the Problems view that hint at failing to find the Closure library, but I've confirmed the Closure base directory in the plugin preferences. I'm able to compile my source with closureBuilder.py without issue.

**Comment by vtst** [comment]
Hi,
Thanks for the bug report. I just submitted a change that should prevent the NullPointerException. However, I've some doubts this would solve all your problems. I did not debug this feature under Windows. Please let me know if you still have some problems with the new version

**Comment by vtst** [comment]
Version 0.2.2 released!

**Comment by SanjayVas** [comment]
I just tested this and while there's no more NPE, it's definitely not handling paths correctly on Windows.

ERROR - Cannot read: d:\Users\SDraconis\Apps\closure-tools\closure-library\d:\Users\SDraconis\Apps\closure-tools\closure-library\d:\Users\SDraconis\Apps\closure-tools\closure-library\closure\goog\array\array.js

Edit: Tried resetting to defaults and readjusting the path and instead got the following:
ERROR - Circular dependency detected: goog -> goog

**Comment by vtst** [comment]
Thanks for the feedback. I suspect the following problem: the plugin does not consider "d:\Users..." as an absolute path, hence path concatenations are not performed correctly. The reason might be that you put the drive letter in lowercase. Could you please try by changing the path of the closure library into "D:\Users..."?

**Comment by SanjayVas** [comment]
Thanks, that indeed fixed the problem. The unfortunate part about this is
that the OS dialog triggered by the "Browse" button appears to return an
absolute path starting with a lower-case drive letter.

On Wed, May 30, 2012 at 4:32 AM, vtst <
reply@reply.github.com

**Comment by vtst** [comment]
Yes, this is unfortunate. And more generally, the plugin should support both lowercase and uppercase letters.
Thanks for doing the check, I'm now sure of what the problem is. I just opened a bug to trace it (#67), and I'll fix it in the next version.
