### ISSUE TITLE
JS: GC overhead limit exceeded

### ISSUE THREAD

**Issue by firecow** [vtst/ow#59]
I've added a library to my project, and eclipse started building that library as well...

The library contains 14473 lines of code, and 167 files.

Project is called LayerBrowser and the library is called JST (Javascript Tools)

-Xms512m
-Xmx1024m

Here is my Eclipse log..

```
!SESSION 2012-05-25 08:53:34.415 -----------------------------------------------
eclipse.buildId=M20120208-0800
java.version=1.6.0_24
java.vendor=Sun Microsystems Inc.
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.core.resources 4 2 2012-05-25 08:55:58.403
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
java.lang.RuntimeException: java.lang.OutOfMemoryError: GC overhead limit exceeded
    at com.google.javascript.jscomp.Compiler.runCallable(Compiler.java:643)
    at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:588)
    at com.google.javascript.jscomp.Compiler.compile(Compiler.java:570)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at net.vtst.ow.closure.compiler.magic.MagicCompiler.compile(MagicCompiler.java:107)
    at net.vtst.ow.closure.compiler.magic.MagicCompiler.compile(MagicCompiler.java:145)
    at net.vtst.ow.closure.compiler.magic.MagicCompiler.compile(MagicCompiler.java:153)
    at net.vtst.ow.closure.compiler.compile.CompilerRun.compile(CompilerRun.java:133)
    at net.vtst.ow.closure.compiler.compile.CompilerRun.<init>(CompilerRun.java:78)
    at net.vtst.ow.closure.compiler.compile.CompilableJSUnit.fullCompile(CompilableJSUnit.java:73)
    at net.vtst.ow.eclipse.js.closure.builder.ClosureBuilder.compileJavaScriptFile(ClosureBuilder.java:301)
    at net.vtst.ow.eclipse.js.closure.builder.ClosureBuilder.compileJavaScriptFiles(ClosureBuilder.java:262)
    at net.vtst.ow.eclipse.js.closure.builder.ClosureBuilder.fullBuild(ClosureBuilder.java:152)
    at net.vtst.ow.eclipse.js.closure.builder.ClosureBuilder.build(ClosureBuilder.java:91)
    at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:728)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:199)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:239)
    at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:292)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:295)
    at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:351)
    at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:374)
    at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
    at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
    at com.google.javascript.rhino.Node.cloneNode(Node.java:1675)
    at com.google.javascript.rhino.Node.cloneTree(Node.java:1692)
    at com.google.javascript.rhino.Node.cloneTree(Node.java:1694)
    at com.google.javascript.rhino.Node.cloneTree(Node.java:1694)
    at com.google.javascript.rhino.Node.cloneTree(Node.java:1694)
    at net.vtst.ow.closure.compiler.deps.AstFactory$ClonedAst.getAstRoot(AstFactory.java:55)
    at com.google.javascript.jscomp.CompilerInput.getAstRoot(CompilerInput.java:119)
    at com.google.javascript.jscomp.Compiler.parseInputs(Compiler.java:1302)
    at com.google.javascript.jscomp.Compiler.parse(Compiler.java:697)
    at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:651)
    at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:70)
    at com.google.javascript.jscomp.Compiler$1.call(Compiler.java:573)
    at com.google.javascript.jscomp.Compiler$1.call(Compiler.java:570)
    at com.google.javascript.jscomp.Compiler$2.run(Compiler.java:615)
    at com.google.javascript.jscomp.Compiler.runCallable(Compiler.java:638)
    at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:588)
    at com.google.javascript.jscomp.Compiler.compile(Compiler.java:570)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at net.vtst.ow.closure.compiler.magic.MagicCompiler.compile(MagicCompiler.java:107)
    at net.vtst.ow.closure.compiler.magic.MagicCompiler.compile(MagicCompiler.java:145)
    at net.vtst.ow.closure.compiler.magic.MagicCompiler.compile(MagicCompiler.java:153)
    at net.vtst.ow.closure.compiler.compile.CompilerRun.compile(CompilerRun.java:133)
    at net.vtst.ow.closure.compiler.compile.CompilerRun.<init>(CompilerRun.java:78)
    at net.vtst.ow.closure.compiler.compile.CompilableJSUnit.fullCompile(CompilableJSUnit.java:73)
    at net.vtst.ow.eclipse.js.closure.builder.ClosureBuilder.compileJavaScriptFile(ClosureBuilder.java:301)
    at net.vtst.ow.eclipse.js.closure.builder.ClosureBuilder.compileJavaScriptFiles(ClosureBuilder.java:262)
    at net.vtst.ow.eclipse.js.closure.builder.ClosureBuilder.fullBuild(ClosureBuilder.java:152)
    at net.vtst.ow.eclipse.js.closure.builder.ClosureBuilder.build(ClosureBuilder.java:91)
    at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:728)

!ENTRY org.eclipse.core.resources 4 2 2012-05-25 08:56:15.150
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
java.lang.RuntimeException: java.lang.OutOfMemoryError: GC overhead limit exceeded
    at com.google.javascript.jscomp.Compiler.runCallable(Compiler.java:643)
    at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:588)
    at com.google.javascript.jscomp.Compiler.compile(Compiler.java:570)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at net.vtst.ow.closure.compiler.magic.MagicCompiler.compile(MagicCompiler.java:107)
    at net.vtst.ow.closure.compiler.magic.MagicCompiler.compile(MagicCompiler.java:145)
    at net.vtst.ow.closure.compiler.magic.MagicCompiler.compile(MagicCompiler.java:153)
    at net.vtst.ow.closure.compiler.compile.CompilerRun.compile(CompilerRun.java:133)
    at net.vtst.ow.closure.compiler.compile.CompilerRun.<init>(CompilerRun.java:78)
    at net.vtst.ow.closure.compiler.compile.CompilableJSUnit.fullCompile(CompilableJSUnit.java:73)
    at net.vtst.ow.eclipse.js.closure.builder.ClosureBuilder.compileJavaScriptFile(ClosureBuilder.java:301)
    at net.vtst.ow.eclipse.js.closure.builder.ClosureBuilder.compileJavaScriptFiles(ClosureBuilder.java:262)
    at net.vtst.ow.eclipse.js.closure.builder.ClosureBuilder.fullBuild(ClosureBuilder.java:152)
    at net.vtst.ow.eclipse.js.closure.builder.ClosureBuilder.build(ClosureBuilder.java:91)
    at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:728)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:199)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:239)
    at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:292)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:295)
    at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:351)
    at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:374)
    at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
    at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
    at com.google.javascript.rhino.head.Parser.propertyAccess(Parser.java:2607)
    at com.google.javascript.rhino.head.Parser.memberExprTail(Parser.java:2509)
    at com.google.javascript.rhino.head.Parser.memberExpr(Parser.java:2484)
    at com.google.javascript.rhino.head.Parser.unaryExpr(Parser.java:2358)
    at com.google.javascript.rhino.head.Parser.mulExpr(Parser.java:2283)
    at com.google.javascript.rhino.head.Parser.addExpr(Parser.java:2266)
    at com.google.javascript.rhino.head.Parser.shiftExpr(Parser.java:2246)
    at com.google.javascript.rhino.head.Parser.relExpr(Parser.java:2220)
    at com.google.javascript.rhino.head.Parser.eqExpr(Parser.java:2191)
    at com.google.javascript.rhino.head.Parser.bitAndExpr(Parser.java:2179)
    at com.google.javascript.rhino.head.Parser.bitXorExpr(Parser.java:2167)
    at com.google.javascript.rhino.head.Parser.bitOrExpr(Parser.java:2155)
    at com.google.javascript.rhino.head.Parser.andExpr(Parser.java:2143)
    at com.google.javascript.rhino.head.Parser.orExpr(Parser.java:2131)
    at com.google.javascript.rhino.head.Parser.condExpr(Parser.java:2107)
    at com.google.javascript.rhino.head.Parser.assignExpr(Parser.java:2077)
    at com.google.javascript.rhino.head.Parser.expr(Parser.java:2055)
    at com.google.javascript.rhino.head.Parser.nameOrLabel(Parser.java:1809)
    at com.google.javascript.rhino.head.Parser.statementHelper(Parser.java:1076)
    at com.google.javascript.rhino.head.Parser.statement(Parser.java:945)
    at com.google.javascript.rhino.head.Parser.statements(Parser.java:900)
    at com.google.javascript.rhino.head.Parser.block(Parser.java:1732)
    at com.google.javascript.rhino.head.Parser.statementHelper(Parser.java:1054)
    at com.google.javascript.rhino.head.Parser.statement(Parser.java:945)
    at com.google.javascript.rhino.head.Parser.ifStatement(Parser.java:1126)
    at com.google.javascript.rhino.head.Parser.statementHelper(Parser.java:991)
    at com.google.javascript.rhino.head.Parser.statement(Parser.java:945)
    at com.google.javascript.rhino.head.Parser.parse(Parser.java:579)
    at com.google.javascript.rhino.head.Parser.parse(Parser.java:517)
    at com.google.javascript.jscomp.parsing.ParserRunner.parse(ParserRunner.java:134)
    at com.google.javascript.jscomp.JsAst.parse(JsAst.java:86)
    at com.google.javascript.jscomp.JsAst.getAstRoot(JsAst.java:52)

!ENTRY org.eclipse.core.resources 4 75 2012-05-25 08:56:15.161
!MESSAGE Errors occurred during the build.
!SUBENTRY 1 net.vtst.ow.eclipse.js.closure 4 75 2012-05-25 08:56:15.161
!MESSAGE Errors running builder 'Closure JavaScript Builder' on project 'JST'.
!STACK 0
java.lang.RuntimeException: java.lang.OutOfMemoryError: GC overhead limit exceeded
    at com.google.javascript.jscomp.Compiler.runCallable(Compiler.java:643)
    at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:588)
    at com.google.javascript.jscomp.Compiler.compile(Compiler.java:570)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at net.vtst.ow.closure.compiler.magic.MagicCompiler.compile(MagicCompiler.java:107)
    at net.vtst.ow.closure.compiler.magic.MagicCompiler.compile(MagicCompiler.java:145)
    at net.vtst.ow.closure.compiler.magic.MagicCompiler.compile(MagicCompiler.java:153)
    at net.vtst.ow.closure.compiler.compile.CompilerRun.compile(CompilerRun.java:133)
    at net.vtst.ow.closure.compiler.compile.CompilerRun.<init>(CompilerRun.java:78)
    at net.vtst.ow.closure.compiler.compile.CompilableJSUnit.fullCompile(CompilableJSUnit.java:73)
    at net.vtst.ow.eclipse.js.closure.builder.ClosureBuilder.compileJavaScriptFile(ClosureBuilder.java:301)
    at net.vtst.ow.eclipse.js.closure.builder.ClosureBuilder.compileJavaScriptFiles(ClosureBuilder.java:262)
    at net.vtst.ow.eclipse.js.closure.builder.ClosureBuilder.fullBuild(ClosureBuilder.java:152)
    at net.vtst.ow.eclipse.js.closure.builder.ClosureBuilder.build(ClosureBuilder.java:91)
    at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:728)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:199)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:239)
    at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:292)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:295)
    at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:351)
    at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:374)
    at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
    at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
    at com.google.javascript.rhino.Node.cloneNode(Node.java:1675)
    at com.google.javascript.rhino.Node.cloneTree(Node.java:1692)
    at com.google.javascript.rhino.Node.cloneTree(Node.java:1694)
    at com.google.javascript.rhino.Node.cloneTree(Node.java:1694)
    at com.google.javascript.rhino.Node.cloneTree(Node.java:1694)
    at net.vtst.ow.closure.compiler.deps.AstFactory$ClonedAst.getAstRoot(AstFactory.java:55)
    at com.google.javascript.jscomp.CompilerInput.getAstRoot(CompilerInput.java:119)
    at com.google.javascript.jscomp.Compiler.parseInputs(Compiler.java:1302)
    at com.google.javascript.jscomp.Compiler.parse(Compiler.java:697)
    at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:651)
    at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:70)
    at com.google.javascript.jscomp.Compiler$1.call(Compiler.java:573)
    at com.google.javascript.jscomp.Compiler$1.call(Compiler.java:570)
    at com.google.javascript.jscomp.Compiler$2.run(Compiler.java:615)
    at com.google.javascript.jscomp.Compiler.runCallable(Compiler.java:638)
    at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:588)
    at com.google.javascript.jscomp.Compiler.compile(Compiler.java:570)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at net.vtst.ow.closure.compiler.magic.MagicCompiler.compile(MagicCompiler.java:107)
    at net.vtst.ow.closure.compiler.magic.MagicCompiler.compile(MagicCompiler.java:145)
    at net.vtst.ow.closure.compiler.magic.MagicCompiler.compile(MagicCompiler.java:153)
    at net.vtst.ow.closure.compiler.compile.CompilerRun.compile(CompilerRun.java:133)
    at net.vtst.ow.closure.compiler.compile.CompilerRun.<init>(CompilerRun.java:78)
    at net.vtst.ow.closure.compiler.compile.CompilableJSUnit.fullCompile(CompilableJSUnit.java:73)
    at net.vtst.ow.eclipse.js.closure.builder.ClosureBuilder.compileJavaScriptFile(ClosureBuilder.java:301)
    at net.vtst.ow.eclipse.js.closure.builder.ClosureBuilder.compileJavaScriptFiles(ClosureBuilder.java:262)
    at net.vtst.ow.eclipse.js.closure.builder.ClosureBuilder.fullBuild(ClosureBuilder.java:152)
    at net.vtst.ow.eclipse.js.closure.builder.ClosureBuilder.build(ClosureBuilder.java:91)
    at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:728)
!SUBENTRY 1 net.vtst.ow.eclipse.js.closure 4 75 2012-05-25 08:56:15.161
!MESSAGE Errors running builder 'Closure JavaScript Builder' on project 'LayerBrowser'.
!STACK 0
java.lang.RuntimeException: java.lang.OutOfMemoryError: GC overhead limit exceeded
    at com.google.javascript.jscomp.Compiler.runCallable(Compiler.java:643)
    at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:588)
    at com.google.javascript.jscomp.Compiler.compile(Compiler.java:570)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at net.vtst.ow.closure.compiler.magic.MagicCompiler.compile(MagicCompiler.java:107)
    at net.vtst.ow.closure.compiler.magic.MagicCompiler.compile(MagicCompiler.java:145)
    at net.vtst.ow.closure.compiler.magic.MagicCompiler.compile(MagicCompiler.java:153)
    at net.vtst.ow.closure.compiler.compile.CompilerRun.compile(CompilerRun.java:133)
    at net.vtst.ow.closure.compiler.compile.CompilerRun.<init>(CompilerRun.java:78)
    at net.vtst.ow.closure.compiler.compile.CompilableJSUnit.fullCompile(CompilableJSUnit.java:73)
    at net.vtst.ow.eclipse.js.closure.builder.ClosureBuilder.compileJavaScriptFile(ClosureBuilder.java:301)
    at net.vtst.ow.eclipse.js.closure.builder.ClosureBuilder.compileJavaScriptFiles(ClosureBuilder.java:262)
    at net.vtst.ow.eclipse.js.closure.builder.ClosureBuilder.fullBuild(ClosureBuilder.java:152)
    at net.vtst.ow.eclipse.js.closure.builder.ClosureBuilder.build(ClosureBuilder.java:91)
    at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:728)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:199)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:239)
    at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:292)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:295)
    at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:351)
    at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:374)
    at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
    at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
    at com.google.javascript.rhino.head.Parser.propertyAccess(Parser.java:2607)
    at com.google.javascript.rhino.head.Parser.memberExprTail(Parser.java:2509)
    at com.google.javascript.rhino.head.Parser.memberExpr(Parser.java:2484)
    at com.google.javascript.rhino.head.Parser.unaryExpr(Parser.java:2358)
    at com.google.javascript.rhino.head.Parser.mulExpr(Parser.java:2283)
    at com.google.javascript.rhino.head.Parser.addExpr(Parser.java:2266)
    at com.google.javascript.rhino.head.Parser.shiftExpr(Parser.java:2246)
    at com.google.javascript.rhino.head.Parser.relExpr(Parser.java:2220)
    at com.google.javascript.rhino.head.Parser.eqExpr(Parser.java:2191)
    at com.google.javascript.rhino.head.Parser.bitAndExpr(Parser.java:2179)
    at com.google.javascript.rhino.head.Parser.bitXorExpr(Parser.java:2167)
    at com.google.javascript.rhino.head.Parser.bitOrExpr(Parser.java:2155)
    at com.google.javascript.rhino.head.Parser.andExpr(Parser.java:2143)
    at com.google.javascript.rhino.head.Parser.orExpr(Parser.java:2131)
    at com.google.javascript.rhino.head.Parser.condExpr(Parser.java:2107)
    at com.google.javascript.rhino.head.Parser.assignExpr(Parser.java:2077)
    at com.google.javascript.rhino.head.Parser.expr(Parser.java:2055)
    at com.google.javascript.rhino.head.Parser.nameOrLabel(Parser.java:1809)
    at com.google.javascript.rhino.head.Parser.statementHelper(Parser.java:1076)
    at com.google.javascript.rhino.head.Parser.statement(Parser.java:945)
    at com.google.javascript.rhino.head.Parser.statements(Parser.java:900)
    at com.google.javascript.rhino.head.Parser.block(Parser.java:1732)
    at com.google.javascript.rhino.head.Parser.statementHelper(Parser.java:1054)
    at com.google.javascript.rhino.head.Parser.statement(Parser.java:945)
    at com.google.javascript.rhino.head.Parser.ifStatement(Parser.java:1126)
    at com.google.javascript.rhino.head.Parser.statementHelper(Parser.java:991)
    at com.google.javascript.rhino.head.Parser.statement(Parser.java:945)
    at com.google.javascript.rhino.head.Parser.parse(Parser.java:579)
    at com.google.javascript.rhino.head.Parser.parse(Parser.java:517)
    at com.google.javascript.jscomp.parsing.ParserRunner.parse(ParserRunner.java:134)
    at com.google.javascript.jscomp.JsAst.parse(JsAst.java:86)
    at com.google.javascript.jscomp.JsAst.getAstRoot(JsAst.java:52)
```

**Comment by firecow** [comment]
-Xms2048m
-Xmx2048m

Made Eclipse compile the JST project after a couple of Eclipse restarts... It still takes a lot of time to build a quite small project, like 3-4 minute or so.

After the build all was working fine.
Its like the js.ow file creation process clutches up memory a lot, at least more than it probably should...

**Comment by vtst** [comment]
Thanks for the bug report. This is strange, because the generation of the js.ow files should be a lightweight process.
Is the library publicly available, so that I can investigate the problem?

**Comment by firecow** [comment]
No, i'm sorry its not...
I'll make some more test tuesday, to see if i can narrow down the bug... 
And ask the project manager if i'm allow to ship you the code...

**Comment by firecow** [comment]
Haven't been able to narrow this down, and can't send you our project...

I'll try to find some opensource project, to locate the same error in. So you can see it for yourself.

**Comment by vtst** [comment]
Ok, thanks!

**Comment by firecow** [comment]
https://github.com/firecow/bigclosureproject.git
Here is a project were the GC Heapexception happens..

-Xms512m
-Xmx1024m

**Comment by vtst** [comment]
Thanks for the feedback, I'll try to have a look.

**Comment by vtst** [comment]
This should be adressed by issue #98.
