### ISSUE TITLE
JS: NullPointerException when cursor is placed at the end of the line containing return stmnt

### ISSUE THREAD

**Issue by deno** [vtst/ow#62]
Example code:

``` javascript

foo.bar = function(x) {
  if (xyz) {
    return fn(x);«error»
  }

  return fn(x);«error»

  return (fn(x));«error»

  return new fn(x);«ok»

  return x;«sometimes»

  return "";«error» 

  return x+"x";«error» 

  return this.x;«error»

  return fn(
      x);«error»

  return new fn(
      x);«ok»

  return;«error»  
};
```

«» — cursor position
«ok» — no error
«error» — triggers error
«sometimes» — I have code that never triggers an exception in that case, but I don’t see a pattern. 

If cursor is at the end of the line of a return, this exception happens:

```
An internal error occurred during: "Requesting JavaScript AST from selection".
java.lang.NullPointerException
```

This doesn’t happen again until the file is closed and reopened. And sometimes the cursor will disappear.

**Comment by vtst** [comment]
Thanks for the bug report, I was able to reproduce it.

java.lang.NullPointerException
    at org.eclipse.wst.jsdt.internal.compiler.lookup.CompilationUnitScope.connectTypeHierarchy(CompilationUnitScope.java:669)
    at org.eclipse.wst.jsdt.internal.compiler.lookup.CompilationUnitScope.connectTypeHierarchy(CompilationUnitScope.java:674)
    at org.eclipse.wst.jsdt.internal.compiler.lookup.LookupEnvironment.completeTypeBindings(LookupEnvironment.java:387)
    at org.eclipse.wst.jsdt.internal.compiler.lookup.LookupEnvironment.completeTypeBindings(LookupEnvironment.java:443)
    at org.eclipse.wst.jsdt.internal.core.CompilationUnitProblemFinder.accept(CompilationUnitProblemFinder.java:174)
    at org.eclipse.wst.jsdt.internal.compiler.lookup.LookupEnvironment.askForBinding(LookupEnvironment.java:279)
    at org.eclipse.wst.jsdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:132)
    at org.eclipse.wst.jsdt.internal.compiler.lookup.LookupEnvironment.getType(LookupEnvironment.java:766)
    at org.eclipse.wst.jsdt.internal.compiler.lookup.LookupEnvironment.getResolvedType(LookupEnvironment.java:720)
    at org.eclipse.wst.jsdt.internal.compiler.lookup.Scope.getJavaLangString(Scope.java:1745)
    at org.eclipse.wst.jsdt.core.dom.DefaultBindingResolver.resolveExpressionType(DefaultBindingResolver.java:604)
    at org.eclipse.wst.jsdt.core.dom.Expression.resolveTypeBinding(Expression.java:111)
    at org.eclipse.wst.jsdt.internal.corext.refactoring.code.flow.ReturnFlowInfo.getReturnFlag(ReturnFlowInfo.java:31)
    at org.eclipse.wst.jsdt.internal.corext.refactoring.code.flow.ReturnFlowInfo.<init>(ReturnFlowInfo.java:19)
    at org.eclipse.wst.jsdt.internal.corext.refactoring.code.flow.FlowAnalyzer.createReturn(FlowAnalyzer.java:151)
    at org.eclipse.wst.jsdt.internal.corext.refactoring.code.flow.FlowAnalyzer.endVisit(FlowAnalyzer.java:679)
    at org.eclipse.wst.jsdt.core.dom.ReturnStatement.accept0(ReturnStatement.java:141)
    at org.eclipse.wst.jsdt.core.dom.ASTNode.accept(ASTNode.java:2354)
    at org.eclipse.wst.jsdt.internal.corext.refactoring.code.flow.InOutFlowAnalyzer.perform(InOutFlowAnalyzer.java:41)
    at org.eclipse.wst.jsdt.internal.ui.search.MethodExitsFinder.markReferences(MethodExitsFinder.java:122)
    at org.eclipse.wst.jsdt.internal.ui.search.MethodExitsFinder.perform(MethodExitsFinder.java:92)
    at org.eclipse.wst.jsdt.internal.ui.javaeditor.JavaEditor.updateOccurrenceAnnotations(JavaEditor.java:2840)
    at org.eclipse.wst.jsdt.internal.ui.javaeditor.JavaEditor$7.selectionChanged(JavaEditor.java:2905)
    at org.eclipse.wst.jsdt.internal.ui.viewsupport.SelectionListenerWithASTManager$PartListenerGroup.calculateASTandInform(SelectionListenerWithASTManager.java:157)
    at org.eclipse.wst.jsdt.internal.ui.viewsupport.SelectionListenerWithASTManager$3.run(SelectionListenerWithASTManager.java:134)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

It seems this is a bug from JSDT, not from the Closure plugin.

**Comment by deno** [comment]
Tracking here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=359005
