### ISSUE TITLE
Project properties menu item javascript | closure, selection yields 'the currently displayed page contains invalid values'

### ISSUE THREAD

**Issue by bytesandwich** [vtst/ow#82]
The associated log event trace:
java.lang.ClassCastException: org.eclipse.jdt.internal.core.JavaProject cannot be cast to org.eclipse.core.resources.IProject
    at net.vtst.ow.eclipse.js.closure.properties.project.ClosureAsbtractPropertyPage.hasNature(ClosureAsbtractPropertyPage.java:65)
    at net.vtst.ow.eclipse.js.closure.properties.project.ClosureMainConfigurationPropertyPage.createContents(ClosureMainConfigurationPropertyPage.java:37)
    at org.eclipse.jface.preference.PreferencePage.createControl(PreferencePage.java:232)
    at org.eclipse.jface.preference.PreferenceDialog.createPageControl(PreferenceDialog.java:1502)
    at org.eclipse.jface.preference.PreferenceDialog$14.run(PreferenceDialog.java:1259)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:49)
    at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:175)
    at org.eclipse.jface.preference.PreferenceDialog.showPage(PreferenceDialog.java:1253)
    at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.showPage(FilteredPreferenceDialog.java:675)
    at org.eclipse.jface.preference.PreferenceDialog$10.run(PreferenceDialog.java:709)
    at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
    at org.eclipse.jface.preference.PreferenceDialog$9.selectionChanged(PreferenceDialog.java:705)
    at org.eclipse.jface.viewers.StructuredViewer$3.run(StructuredViewer.java:888)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:49)
    at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:175)
    at org.eclipse.jface.viewers.StructuredViewer.firePostSelectionChanged(StructuredViewer.java:886)
    at org.eclipse.jface.viewers.StructuredViewer.handlePostSelect(StructuredViewer.java:1226)
    at org.eclipse.jface.viewers.StructuredViewer$5.widgetSelected(StructuredViewer.java:1251)
    at org.eclipse.jface.util.OpenStrategy.firePostSelectionEvent(OpenStrategy.java:262)
    at org.eclipse.jface.util.OpenStrategy.access$5(OpenStrategy.java:256)
    at org.eclipse.jface.util.OpenStrategy$3.run(OpenStrategy.java:433)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3944)
    at org.eclipse.swt.widgets.Display.observerProc(Display.java:3534)
    at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
    at org.eclipse.swt.widgets.Display.applicationNextEventMatchingMask(Display.java:4873)
    at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5239)
    at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
    at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:221)
    at org.eclipse.swt.widgets.Widget.mouseDownSuper(Widget.java:1093)
    at org.eclipse.swt.widgets.Tree.mouseDownSuper(Tree.java:2052)
    at org.eclipse.swt.widgets.Widget.mouseDown(Widget.java:1085)
    at org.eclipse.swt.widgets.Control.mouseDown(Control.java:2538)
    at org.eclipse.swt.widgets.Tree.mouseDown(Tree.java:2007)
    at org.eclipse.swt.widgets.Display.windowProc(Display.java:5493)
    at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
    at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:221)
    at org.eclipse.swt.widgets.Widget.windowSendEvent(Widget.java:2102)
    at org.eclipse.swt.widgets.Shell.windowSendEvent(Shell.java:2284)
    at org.eclipse.swt.widgets.Display.windowProc(Display.java:5557)
    at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
    at org.eclipse.swt.widgets.Display.applicationSendEvent(Display.java:5002)
    at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5151)
    at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
    at org.eclipse.swt.internal.cocoa.NSApplication.sendEvent(NSApplication.java:128)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3616)
    at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
    at org.eclipse.jface.window.Window.open(Window.java:801)
    at org.eclipse.ui.dialogs.PropertyDialogAction.run(PropertyDialogAction.java:158)
    at org.eclipse.jface.action.Action.runWithEvent(Action.java:498)
    at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:584)
    at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:501)
    at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:411)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4134)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1458)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1481)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1466)
    at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1271)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3980)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3619)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1022)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:916)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:86)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:585)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:540)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1438)

**Comment by bytesandwich** [comment]
steps to reproduce: install eclipse (eclipse-SDK-4.2-macosx-cocoa-x86_64.tar.gz)

with plugins:
    (juno, eclipse web developer tools)
    Eclipse SDK 4.2.0.I20120608-1400
      Eclipse Project SDK   4.2.0.v20120528-1648-7T7oDFDPz-3FepgRqG6kkFFY0UF4_otgmt0XcoU3Zh27X
      Equinox p2 Provisioning for IDEs. 2.2.0.v20120524-0542-62DG9JXTlSiz-UbcP0w0KGe8CBOP
    Eclipse Web Developer Tools 3.4.0.v201203141800-7O7MFsGEMkBJz0rWbgfTLwn-4WKIocbP_pkka3Il
      Eclipse XML Editors and Tools 3.4.0.v201111021744-7H7GFeBDxumUpsl5liePhK3loz-m62J4rSz011R1
      JavaScript Development Tools  1.4.0.v201111090639-7H7DFeHFC7sRemSZgYbe4
      WST Common UI 3.4.0.v201203141800-7C7AFeBEdhOawe9e8mNfykJqRz00Q0RT
      WST Server UI 3.3.100.v20110810_1722-7B7AFGHAtMcLXxbGc-IjRefCA84
      WST Web Core  3.4.0.v201203141800-7E7HFSgAJz-mw9oH21HGMpHiKb_kVAz0D
        WST Common Core 3.4.0.v201107190500-7B7EFMSF7RZHOjIpQz-P-QS
        WST Server Core 3.3.100.v20110810_1722-33Et8s73563B6Ha3113
        WST XML Core    3.4.0.v201111021744-7C7OFm4F7RZHQRIpOz-P2Xk
      WST Web User Documentation    3.3.0.v201102200555-31Eo8s734B3E4H7799

(your javascript plugin)
Ow JavaScript   0.2.7

create a new java project, add javascript facet, open project properties select javascript | closure -> see error

**Comment by bytesandwich** [comment]
I have a fairly complicated project, so I just wanted to see if the issue occurs on a fresh install/project

I noted that I don't receive this error if it is just a javascript project.

**Comment by vtst** [comment]
Thanks for the bug report. I just fixed the issue in the code base. The fix will be available in the next release.

**Comment by bytesandwich** [comment]
Thank you for maintaining the super useful plugin.
