### ISSUE TITLE
javascript closure linter run configuration: fix lint errors -> fixjsstyle doesn't take --nobeep

### ISSUE THREAD

**Issue by bytesandwich** [vtst/ow#89]
```
Traceback (most recent call last):
  File "/usr/local/bin/fixjsstyle", line 8, in <module>
    load_entry_point('closure-linter==2.3.6.1', 'console_scripts', 'fixjsstyle')()
  File "build/bdist.macosx-10.8-intel/egg/closure_linter/fixjsstyle.py", line 43, in main
  File "build/bdist.macosx-10.8-intel/egg/gflags.py", line 1319, in __call__
gflags.UnrecognizedFlagError: Unknown command line flag 'nobeep'
```

I think you are [reusing jslinter config for fixstyle](https://github.com/vtst/ow/blob/master/src/eclipse/net.vtst.ow.eclipse.js.closure/src/net/vtst/ow/eclipse/js/closure/launching/linter/ClosureLinterLaunchConfigurationDelegate.java#L77)

**Comment by vtst** [comment]
Thanks for the bug report. This is fixed in the code base, and will be released in the next version.
